{{- if .Values.ingress.traefik -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-api
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.api.domain }}`)
      kind: Rule
      services:
        - name: api-svc
          port: 80
      middlewares:
        - name: traefik-compress
          namespace: traefik
        - name: stripprefix-api
  tls:
    certResolver: letsencrypt
    domains:
      - main: {{ .Values.api.domain | quote }}
{{- end -}}
