apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: pipem.io
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: '{{ .Values.images.app }}'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js
          # resources:
          #   limits:
          #     memory: '32Mi'
          #     cpu: '10m'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: app-config
