apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: pipem.io
    component: api
spec:
  selector:
    component: api
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
